#!/bin/bash -
set -o nounset

# Disable the built in screensaver and show wallpaper
if command -v gsettings
then
  gsettings set org.gnome.desktop.session idle-delay 0
  gsettings set org.cinnamon.desktop.session idle-delay 0
  gsettings set org.mate.screensaver idle-activation-enabled false
fi

if command -v xset
then
  sleep 1; xset s off
  sleep 1; xset s noblank
fi

export XSECURELOCK_NO_COMPOSITE=1
export XSECURELOCK_SHOW_USERNAME=1
export XSECURELOCK_SHOW_DATETIME=0
export XSECURELOCK_AUTH_TIMEOUT=30
export XSECURELOCK_AUTH_SOUNDS=1
export XSECURELOCK_BLANK_TIMEOUT=-1
export XSECURELOCK_BLANK_DPMS_STATE="on"
export XSECURELOCK_PASSWORD_PROMPT="asterisks"
export XSECURELOCK_FONT="-*-helvetica-medium-r-normal-*-18-*-*-*-*-*-*"
export XSECURELOCK_COMPOSITE_OBSCURER=0
export XSECURELOCK_SAVER=/usr/local/share/nsls2/bin/saver-nsls2

/usr/bin/xautolock -time 1 \
  -secure \
  -locker /usr/bin/xsecurelock
